# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('location_answer', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('answer_latitude', models.FloatField(null=True)),
                ('answer_longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='play.Trail'),
        ),
    ]
