# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieQuestionTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookieTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookies', to='play.Trail')),
            ],
        ),
        migrations.AddField(
            model_name='cookiequestiontracker',
            name='cookie_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_questions', to='play.CookieTracker'),
        ),
        migrations.AddField(
            model_name='cookiequestiontracker',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookies', to='play.CookieTracker'),
        ),
    ]
