# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20161228_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookietracker',
            name='cookie_id',
        ),
        migrations.AlterField(
            model_name='cookietracker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
