# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20161228_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiequestiontracker',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookies', to='play.Question'),
        ),
    ]
