# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20161228_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_questions', to='play.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TrailCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trail_cookies', to='play.Trail')),
            ],
        ),
        migrations.RemoveField(
            model_name='cookiequestiontracker',
            name='cookie_tracker',
        ),
        migrations.RemoveField(
            model_name='cookiequestiontracker',
            name='question',
        ),
        migrations.RemoveField(
            model_name='cookietracker',
            name='trail',
        ),
        migrations.DeleteModel(
            name='CookieQuestionTracker',
        ),
        migrations.DeleteModel(
            name='CookieTracker',
        ),
        migrations.AddField(
            model_name='correctquestion',
            name='trail_cookie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_questions', to='play.TrailCookie'),
        ),
    ]
